// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "github.com/wen-flower/easy-douyin/kitex_gen/user"
)

func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

var userServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{
		"CreateUser":   kitex.NewMethodInfo(createUserHandler, newUserServiceCreateUserArgs, newUserServiceCreateUserResult, false),
		"CheckUser":    kitex.NewMethodInfo(checkUserHandler, newUserServiceCheckUserArgs, newUserServiceCheckUserResult, false),
		"QueryUser":    kitex.NewMethodInfo(queryUserHandler, newUserServiceQueryUserArgs, newUserServiceQueryUserResult, false),
		"FollowUser":   kitex.NewMethodInfo(followUserHandler, newUserServiceFollowUserArgs, newUserServiceFollowUserResult, false),
		"FollowList":   kitex.NewMethodInfo(followListHandler, newUserServiceFollowListArgs, newUserServiceFollowListResult, false),
		"FollowerList": kitex.NewMethodInfo(followerListHandler, newUserServiceFollowerListArgs, newUserServiceFollowerListResult, false),
		"FriendList":   kitex.NewMethodInfo(friendListHandler, newUserServiceFriendListArgs, newUserServiceFriendListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func createUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCreateUserArgs)
	realResult := result.(*user.UserServiceCreateUserResult)
	success, err := handler.(user.UserService).CreateUser(ctx, realArg.Param)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCreateUserArgs() interface{} {
	return user.NewUserServiceCreateUserArgs()
}

func newUserServiceCreateUserResult() interface{} {
	return user.NewUserServiceCreateUserResult()
}

func checkUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCheckUserArgs)
	realResult := result.(*user.UserServiceCheckUserResult)
	success, err := handler.(user.UserService).CheckUser(ctx, realArg.Param)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCheckUserArgs() interface{} {
	return user.NewUserServiceCheckUserArgs()
}

func newUserServiceCheckUserResult() interface{} {
	return user.NewUserServiceCheckUserResult()
}

func queryUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceQueryUserArgs)
	realResult := result.(*user.UserServiceQueryUserResult)
	success, err := handler.(user.UserService).QueryUser(ctx, realArg.Param)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceQueryUserArgs() interface{} {
	return user.NewUserServiceQueryUserArgs()
}

func newUserServiceQueryUserResult() interface{} {
	return user.NewUserServiceQueryUserResult()
}

func followUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceFollowUserArgs)
	realResult := result.(*user.UserServiceFollowUserResult)
	success, err := handler.(user.UserService).FollowUser(ctx, realArg.Param)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceFollowUserArgs() interface{} {
	return user.NewUserServiceFollowUserArgs()
}

func newUserServiceFollowUserResult() interface{} {
	return user.NewUserServiceFollowUserResult()
}

func followListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceFollowListArgs)
	realResult := result.(*user.UserServiceFollowListResult)
	success, err := handler.(user.UserService).FollowList(ctx, realArg.Param)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceFollowListArgs() interface{} {
	return user.NewUserServiceFollowListArgs()
}

func newUserServiceFollowListResult() interface{} {
	return user.NewUserServiceFollowListResult()
}

func followerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceFollowerListArgs)
	realResult := result.(*user.UserServiceFollowerListResult)
	success, err := handler.(user.UserService).FollowerList(ctx, realArg.Param)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceFollowerListArgs() interface{} {
	return user.NewUserServiceFollowerListArgs()
}

func newUserServiceFollowerListResult() interface{} {
	return user.NewUserServiceFollowerListResult()
}

func friendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceFriendListArgs)
	realResult := result.(*user.UserServiceFriendListResult)
	success, err := handler.(user.UserService).FriendList(ctx, realArg.Param)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceFriendListArgs() interface{} {
	return user.NewUserServiceFriendListArgs()
}

func newUserServiceFriendListResult() interface{} {
	return user.NewUserServiceFriendListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateUser(ctx context.Context, param *user.CreateUserParam) (r *user.CreateUserResp, err error) {
	var _args user.UserServiceCreateUserArgs
	_args.Param = param
	var _result user.UserServiceCreateUserResult
	if err = p.c.Call(ctx, "CreateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckUser(ctx context.Context, param *user.CheckUserParam) (r *user.CheckUserResp, err error) {
	var _args user.UserServiceCheckUserArgs
	_args.Param = param
	var _result user.UserServiceCheckUserResult
	if err = p.c.Call(ctx, "CheckUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUser(ctx context.Context, param *user.QueryUserParam) (r *user.QueryUserResp, err error) {
	var _args user.UserServiceQueryUserArgs
	_args.Param = param
	var _result user.UserServiceQueryUserResult
	if err = p.c.Call(ctx, "QueryUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowUser(ctx context.Context, param *user.FollowUserParam) (r *user.FollowUserResp, err error) {
	var _args user.UserServiceFollowUserArgs
	_args.Param = param
	var _result user.UserServiceFollowUserResult
	if err = p.c.Call(ctx, "FollowUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowList(ctx context.Context, param *user.FollowListParam) (r *user.FollowListResp, err error) {
	var _args user.UserServiceFollowListArgs
	_args.Param = param
	var _result user.UserServiceFollowListResult
	if err = p.c.Call(ctx, "FollowList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowerList(ctx context.Context, param *user.FollowerListParam) (r *user.FollowerListResp, err error) {
	var _args user.UserServiceFollowerListArgs
	_args.Param = param
	var _result user.UserServiceFollowerListResult
	if err = p.c.Call(ctx, "FollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FriendList(ctx context.Context, param *user.FriendListParam) (r *user.FriendListResp, err error) {
	var _args user.UserServiceFriendListArgs
	_args.Param = param
	var _result user.UserServiceFriendListResult
	if err = p.c.Call(ctx, "FriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
